apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: marvin
spec:
  selector:
    matchLabels:
      app: marvin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: marvin
    spec:
      containers:
      - name: marvinserver
        image: emdoyle/marvin:latest
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: tcp-marvin
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    developer: {{ .Values.developer | default "emdoyle" | lower | quote }}
spec:
  ports:
  - port: 8080
    name: tcp-marvin
    targetPort: tcp-marvin
  selector:
    app: marvin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  label:
    developer: {{ .Values.developer | default "emdoyle" | lower | quote }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: tcp-marvin
      name: https
  selector:
    app: marvin
