apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: marvin
spec:
  selector:
    matchLabels:
      app: marvin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: marvin
    spec:
      # TODO: secrets for DB creds
      containers:
      - name: marvinserver
        image: emdoyle/marvin:latest
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: tcp-marvin
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
