apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    developer: {{ .Values.developer | default "emdoyle" | lower | quote }}
spec:
  ports:
  - port: 8080
    name: tcp-marvin
    targetPort: tcp-marvin
  selector:
    app: marvin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  label:
    developer: {{ .Values.developer | default "emdoyle" | lower | quote }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: tcp-marvin
      name: https
  selector:
    app: marvin
